### PR TITLE
Add select/deselect all orgunits in tree

### PR DESCRIPTION
**Pull request by tokland**
Closes https://github.com/EyeSeeTea/dataset-configuration/issues/286

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland This seems to work smoothly. I have just made some cosmetics changes. I have committed them to this branch and I have created another branch for dataset configuration that contains the new strings: https://github.com/EyeSeeTea/dataset-configuration/tree/feature/dataset-configuration-orgunits-select-all-286

Can you have a look at them and let me know your thoughts? If you are OK with them I will merge this branch

**Comment by tokland** [comment]
What do you think of adding some visual structure to differentiate filter boxes?

screenshot from 2018-05-16 12-12-45

I've used a material-ui Card. Not sure about the border, we can hide them and still keep the margins to separate the filter boxes

**Comment by adrianq** [comment]
Yes, it makes sense. I would keep the borders as well. Maybe... can we make the tree box height larger so the bottom border aligns with the one on the right?

**Comment by tokland** [comment]
Done, bottom boxes aligned.

**Pull request merged**
